### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by classikd** [Itee/threejs-full-es6#1]
Hello,

I would like to use the files you've adapted for ES6 in my application.
I include them like that for instance:
`import { ShaderPass } from 'threejs-full-es6/sources/postprocessing/ShaderPass'`

But sometimes i encounter problems with some dependencies which are missing.
For example in ShaderPass.js, i had to add this line to make it works:
`import { UniformsUtils } from '../renderers/shaders/UniformsUtils.js'`

Do I forget a step ?
I tried to use patch & build commands, but then i don't really understand what file to use  :/

Thank you

**Comment by Itee** [comment]
You're right there is effectively a missing import ! I will fix it soon.

**Comment by Itee** [comment]
Fixed in 2.1.1 !
Could you confirm ?

**Comment by classikd** [comment]
Thanks, i think this file is ok now.
I've also seen missing dependencies in _UnrealBloomPass.js_ :
LuminosityHighPassShader, UniformsUtils and CopyShader

I encountered some other little problems but not related to dependencies, i think i will create new issue for each.

**Comment by Itee** [comment]
Ok thanks for the feedback. I will start a test to reveal missing deps in all files
