### ISSUE TITLE
UMD build issue -- "Loader" appends "$1" inconsistently

### ISSUE THREAD

**Issue by mattmm3d** [Itee/threejs-full-es6#14]
**Description**

When using the OBJLoader the library would throw an error on a load because it thought that "Loader" did not exist.  It turns out that the UMD build appends "$1" to global variables, but it didn't do it consistently.  I am not sure why, but some of the references to Loader$1 don't have the "$1" appended.  

I don't know enough about UMD to even guess what happened during the build process.

**Here's the full error if anyone is really interested:**

columnNumber: 11
fileName: "http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b"

lineNumber: 192806
​
message: "Loader is not defined"
​
stack: "loadTexture@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:192806:11\nsetMapForType@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:192645:19\ncreateMaterial_@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:192687:13\ncreate@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:192608:9\npreload@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:192574:9\nonMtlLoad@http://localhost:3000/app/app.js?hash=9a111c8f6e0bbdbf50c4667ead6236cd50cff9f2:117:13\nload/<@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:192306:9\nload/<@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:145703:38\nzone.js/</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:251729:17\nonInvokeTask@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:6251:24\nzone.js/</Zone$1</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:251728:17\nzone.js/</Zone$1</Zone</Zone.prototype.runTask@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:251496:28\nzone.js/</Zone$1</ZoneTask</ZoneTask.invokeTask@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:251803:24\ninvokeTask@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:252844:9\nglobalZoneAwareCallback@http://localhost:3000/packages/modules.js?hash=46576314c50b796413508f325387c5546a838a9b:252870:17\n"

**Comment by mattmm3d** [comment]
Also, I fixed this by hand in [my fork](https://github.com/mattmm3d/threejs-full-es6) if you want to see exactly where this popped up.  Obviously this is just a super short term solution so I could keep on developing.  Would be great to figure out the root cause.

**Comment by Itee** [comment]
Are you trying to use OBJLoader or OBJLoader2 ?
Any of them need to include Loader... this is weird ! Maybe a missing dependency...

**Comment by mattmm3d** [comment]
This was when I was using OBJLoader.  I recently switched to OBJLoader2, but this should probably be an easy switch.

You are 100% right though.  I think that issue is actually in MaterialLoader.js. It uses Loader but doesn't have an import for `{Loader } from '../loaders/Loader.js'`

Do you want me to put in a pull request for this?

**Comment by mattmm3d** [comment]
I'm having different issues with the newest release, but this seems to be fixed. I think that this specific can be closed.

**Comment by Itee** [comment]
Ok thanks for the feedback.

Could you open new issues with the newest release ?
