### ISSUE TITLE
OBJLoader2 doesn't work if all materials don't have texture

### ISSUE THREAD

**Issue by mattmm3d** [Itee/threejs-full-es6#16]
I loaded an OBJ file using OBJLoader.  The OBJ had a related material file.  One of the materials didn't have a texture, hence no texture coordinates in the OBJ.  Then there were 3 materials with textures, and texture coordinates in the OBJ ('vt' vertices).  This means that some faces had vt vertices and others didn't. 

In `RawMesh.prototype.buildFace` there is a section where the loader pushes indices to the variable used to create the geometry.  The issue is that when there are texture coordinates for some faces and not for others then the object counts get all out of whack. I fixed the issue by just pushing uv indices even if the face being parsed didn't have a vt vertex.  This just fills the array with a `NaN` (which is the same thing that happens in the original OBJLoader.  I have a feeling that the same thing would happen if some faces had normal vertices and others didn't.

I'm not sure about the spec for OBJ files.  This file can be read by other programs, so I think that the file is probably fine, and that the problem lies in how it's being parsed.  Either `buildFace` needs to pass `NaN` or the code that processes the parsed faces needs to change something.

**Comment by mattmm3d** [comment]
Fixed in the 5.0.X updates.  Feel free to close this one!

Also, I guess it probably makes sense to not open up issues that are solely about implementation.  I'll re-direct those to the main threejs project.

**Comment by Itee** [comment]
You're welcome !
