### ISSUE TITLE
LoaderSupport breaks when using async option in ObjLoader2

### ISSUE THREAD

**Issue by narmadham** [Itee/threejs-full-es6#18]
The following line(66020) breaks

workerCode += 'THREE = { LoaderSupport: {} };\n\n';

It works fine when I replace it with 

workerCode += 'var LoaderSupport = {};\n\n';

It would be great it if it can be fixed.

**Comment by Itee** [comment]
I will get a look, thanks.

**Comment by Itee** [comment]
This should be fixed in release v5.0.6.

Thanks for the feedback.
Best regards.
