### ISSUE TITLE
Uncaught TypeError: FunctionNode is not a constructor     at three:84450

### ISSUE THREAD

**Issue by DanielJoyce** [Itee/threejs-full-es6#2]
Trying to use threejs-full-es6/builds/Three.es.js

Constructor is being called before FunctionNode is defined.

**Comment by DanielJoyce** [comment]
This is because FunctionNode has a cyclic dependency on NodeLib, which is bad....

**Comment by Itee** [comment]
Thank for the feedback, i will take a look about this cyclic dependency.

**Comment by Itee** [comment]
This should be fixed in v4.1.1. Could you confirm ?

**Comment by DanielJoyce** [comment]
Will check tomorrow.

**Comment by DanielJoyce** [comment]
This seems fixed but encountered another bug.
