### ISSUE TITLE
LineSegments: THREE.Object3D.add: object not an instance of THREE.Object3D.

### ISSUE THREAD

**Issue by DanielJoyce** [Itee/threejs-full-es6#3]
Seems that prototype for LineSegments is not set up properly, works with regular threejs, breaks with this version.

**Comment by DanielJoyce** [comment]
Weird, becaue checking the code, it looks like LineSegments does inherit from Line which inherits from Object3D....

**Comment by DanielJoyce** [comment]
which defines isObject3D.

**Comment by DanielJoyce** [comment]
Looks like inheritance chain is broke, LineSegments -> Line -> Object ( instead of Object3D ).

This is in Three.es.js artifact

**Comment by DanielJoyce** [comment]
Ugh, Linesegments was declared in the rollup file before Line, manually patching by cutting and pasting, and fixing the order fixed the issue.

Something is borked with your rollup code. Does your tool not handle deps properly?

**Comment by DanielJoyce** [comment]
Since core threejs is now es6 module based, it makes sense to me to just use the es6 module artifact for that, and then massage all the non-es6 files ( examples, extras, etc ) into es6.

Then use rollup js to combine the threejs e6 module with the converted files.

That should properly handle dependencies, and simplify es6-converter.

**Comment by DanielJoyce** [comment]
Something like facebook codeshift to modify the ast to change global THREE definitions to imports/exports.

**Comment by Itee** [comment]
Thank for the feedback.

> Since core threejs is now es6 module based, it makes sense to me to just use the es6 module artifact for that, and then massage all the non-es6 files ( examples, extras, etc ) into es6.

This could simplify the converter but, i have in mind to use some javascript parser in the future and upgrade all three js files to the latest es7-8-9 standard (using let const etc...) in all the library.

> Linesegments was declared in the rollup file before Line, manually patching by cutting and pasting, and fixing the order fixed the issue.

> Something is borked with your rollup code. Does your tool not handle deps properly?

Which config file ? `rollup.conf.js` doesn't set the file order at all. `rollup.tests.conf.js` will create one bundle per file to be sure that dependencies are correctly set.

Currently, I am unable to reproduce the issues using this code:

```html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Three Full ES6 Tests</title>
	</head>
	<body>
		<script src="LineSegments.test.js"></script>
		<script>
			var line = new Three.LineSegments()
                        alert(line)
		</script>
	</body>
</html>
```

to build `LineSegments.test.js` you should use the npm script `npm run build-test`. The test bundle seems to be correctly formatted without any error. 

Have you other imports in you project that could make conflict with it ? What is the way you're using to bundle ?

> Looks like inheritance chain is broke, LineSegments -> Line -> Object ( instead of Object3D ).
> This is in Three.es.js artifact

In Three.es.js i see:

```javascript
function LineSegments( geometry, material ) {

	Line.call( this, geometry, material );

	this.type = 'LineSegments';

}

LineSegments.prototype = Object.assign( Object.create( Line.prototype ), {

	constructor: LineSegments,

	isLineSegments: true

} );

function Line( geometry, material, mode ) {

	if ( mode === 1 ) {

		console.warn( 'THREE.Line: parameter THREE.LinePieces no longer supported. Created THREE.LineSegments instead.' );
		return new LineSegments( geometry, material );

	}

	Object3D.call( this );

	/* ... */

}

Line.prototype = Object.assign( Object.create( Object3D.prototype ), { /* ... */ } );
```

So maybe a circular reference here in Line ctor ?

**Comment by DanielJoyce** [comment]
Line needs to be declared before LineSegments

Ordering is important.

**Comment by Itee** [comment]
I know that ordering is important.

But in this case LineSegments is use inside the Line ctor, so i can't just move Line before LineSegments, but create middle files to fix it properly. 

Any way could you provide an example with the error, please ?

**Comment by DanielJoyce** [comment]
I found a workaround for regular threejs examples, and went back to my older code.
All I remember is i got a stack trace when trying to use LineSegments.

three:3736 THREE.Object3D.add: object not an instance of THREE.Object3D. LineSegments {uuid: "B8D09BB3-68B9-4CD4-8382-821B952B5133", name: "", type: "LineSegments", parent: null, children: Array(0), …}

To me this indicated that LineSegments -> Line -> Object3d hierarchy was borked, possibly because Line was referenced before its creation

**Comment by Itee** [comment]
> went back to my older code.

Sorry about that ! But... v4.2.4 should fix this issues.

Could you confirm (in case you give a new try), thanks ?

**Comment by Itee** [comment]
I close due to the fix, if not please re-open.

Best regards.
