### ISSUE TITLE
Unable to convert some files

### ISSUE THREAD

**Issue by claudioviola** [Itee/threejs-full-es6#4]
Hello!
Great repo but I've some issue like follow:

Unable to find specific path part for: 
myapp/node_modules/threejs-full-es6/node_modules/three/examples/js
Convert:
myapp/node_modules/threejs-full-es6/node_modules/three/examples/js/AnimationClipCreator.js
myapp/node_modules/threejs-full-es6/sources/AnimationClipCreator.js

'convert-three' errored after 373 ms
Error: Unable to find specific path part for: 
myapp/node_modules/threejs-full-es6/node_modules/three/examples/js/AnimationClipCreator.js

Is it my fault?
Claudio

**Comment by Itee** [comment]
Thank for the feedback !

Have you apply the patch script `npm run patch` before running `npm run convert` ? Care this patch must be apply only once after cloning the repo !!!

**Comment by Itee** [comment]
In case you have some doubts here the install process if you are cloning the repo.

`npm install`
`npm run patch`
`npm run convert`
`npm run build`

then if you change something in configs, or es6-convertor run only convert and build command

In case somethings is broken. Delete you node_module folder and run the previous commands.

**Comment by Itee** [comment]
Ohhh ok i see... you did `npm install three-full-es6` in you app right ?

So you do not need to run convert at all ! Just use one of the builded files.

To import three stuff use this import type:

`import { AnimationClipCreator } from './node_modules/threejs-full-es6/builds/Three.es.js'`

This should do the job ?

**Comment by claudioviola** [comment]
>Ohhh ok i see... you did npm install three-full-es6 in you app right ?
Yes I did.

I'll try your solution.

Thanks!

**Comment by Itee** [comment]
Using:

`import { AnimationClipCreator } from './node_modules/threejs-full-es6/builds/Three.es.js'` will give you the all access to all three stuff. Three.es.js export all classes.

Howerver, you could directly import from source folder too using:

`import { AnimationClipCreator } from './node_modules/threejs-full-es6/sources/AnimationClipCreator.js'`

but you will need to find where sources are located in the folder tree.

Is this good ?

**Comment by Itee** [comment]
/ping @claudioviola

Could i close ?

**Comment by claudioviola** [comment]
Sorry @Itee I can't try at moment. Close and next I'll send you updates.
Thanks a lot!

**Comment by Itee** [comment]
Ok, i will close.

A major release will come soon, and some files from examples will move in the folder tree so if you use the named import from sources files, it will could require some changes.

For example here:

```javascript
import { AnimationClipCreator } from './node_modules/threejs-full-es6/sources/AnimationClipCreator.js'

// become

import { AnimationClipCreator } from './node_modules/threejs-full-es6/sources/animation/AnimationClipCreator.js'

```
