### ISSUE TITLE
Cannot assign to read-only property 'exports' of object '#'

### ISSUE THREAD

**Issue by jean-noelp** [Itee/threejs-full-es6#5]
Hello,

I'm trying to build your looking great package with webpack, but I encounter this issue :

![capture d ecran 2018-01-18 a 09 56 51](https://user-images.githubusercontent.com/28710922/35089133-4dcae0d6-fc36-11e7-95ca-789d9c8c69ce.png)

Could you help me ?

**Comment by Itee** [comment]
This part should be removed... I will take a look deeper, and come back soon.

**Comment by Itee** [comment]
The release v4.2.3 should fix it.

Could you confirm, thanks ?

**Comment by jean-noelp** [comment]
I confirm ! Thank you !

**Comment by Itee** [comment]
You're welcome !

So i close.

**Comment by dgoexail** [comment]
@Itee Looks like the 5.0.1 brings back this bug.

Uncaught TypeError: Cannot assign to read only property 'exports' of object '[object Object]' at ligne 29771 where: 

// browserify support
if ( true ) {
	module.exports = Detector;
}

**Comment by Itee** [comment]
The 5.0.2 should fix it again... Sorry for the disagreement !
