### ISSUE TITLE
isPowerOfTwo does not exist on Math

### ISSUE THREAD

**Issue by dgoexail** [Itee/threejs-full-es6#8]
Hi,

There is a little typo on some of the usage of isPowerOfTwo (in Water.js line 78 for example).
The function is used from the Math Javascript library and not the _Math functions from Three.js.

Would appreciate if you could fix it as i couldn't figure out how to submit a pull request !

Thank you.

**Comment by Itee** [comment]
Sorry to being late and thanks for the feed back.

It will be fixed in the next major release v5.0.0 that should be available this night or tomorrow.

Could you confirm that it will be fixed ?

Best regards
