### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by ksabariraj** [Itee/threejs-full-es6#9]
Hi,

I am getting the below error. Could you please help me on this?

build.js:1 SyntaxError: 'import' and 'export' may only appear at the top level (127829:0) while parsing \node_modules\threejs-full-es6\builds\Three.es.js while parsing file: \node_modules\threejs-full-es6\builds\Three.es.js

Thanks,
Sabari.

**Comment by kirillovdm** [comment]
I had the same error using browserify (+babelify). I decided to use Webpack and it solve the problem

**Comment by Itee** [comment]
I haven't test to build the lib under browserify !

But instead of using import like this:

```javascript
import { foobar } from 'threejs-full-es6'
```

you could try:

```javascript
import { foobar } from './node_module/threejs-full-es6/sources/foobar.js'
```

The build work with rollup too.

**Comment by Diakov94** [comment]
This syntax error appears only if you are using import or export in non-top scope
For example:
```javascript
if (process.env.NODE_ENV === 'production') {
    import { Mesh } from 'threejs-full-es6';
} else {
    import * as THREE from 'threejs-full-es6';
}
```
You can't use like that. If you want to create different variants of bundles depends on node_env, you should do this in webpack config (or w/e you are using).

**Comment by Itee** [comment]
/ping @ksabariraj 
Still an issue ?

**Comment by ksabariraj** [comment]
Hey,

Sorry for the delay. It fixed.

Thanks for your time and help,
Sabari.
